version: "3.3"
services:
  qbittorrent:
    container_name: qBittorrent
    environment:
      - TZ=Asia/Shanghai
      - TemPath=/downloads
      - SavePath=/downloads
      - PGID=1000
      - PUID=1000
      - WEBUI_PORT=8080
    volumes:
      - ${QB_CONFIG_PATH}:/config # 填入实际地址
      - ${DOWNLOAD_PATH}:/downloads # 填入下载绝对路径
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      - auto_bangumi
    restart: unless-stopped
    image: lscr.io/linuxserver/qbittorrent:4.4.3

  auto_bangumi:
    container_name: AutoBangumi
    environment:
      - TZ=Asia/Shanghai
      - AB_INTERVAL_TIME=1800
      - AB_DOWNLOADER_HOST=localhost:8080
      - AB_DOWNLOADER_USERNAME=admin
      - AB_DOWNLOADER_PASSWORD=adminadmin
      - AB_METHOD=pn
      - AB_GROUP_TAG=True
      - AB_NOT_CONTAIN=720
      - AB_DOWNLOAD_PATH=${DOWNLOAD_PATH}
      - AB_RSS=${RSS}
      - AB_RULE_DEBUG=False
      - AB_DEBUG_MODE=False
      - AB_EP_COMPLETE=True
      - AB_SEASON_ONE=True
    networks:
      - auto_bangumi
    dns:
      - 8.8.8.8
      - 223.5.5.5
    restart: unless-stopped
    image: estrellaxd/auto_bangumi:latest
    depends_on:
      - qbittorrent

networks:
  auto_bangumi:
