version: "3.4"

services:
  AutoBangumi:
    image: "ghcr.io/estrellaxd/auto_bangumi:latest"
    container_name: AutoBangumi
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    network_mode: bridge
    ports:
      - "7892:7892"
    restart: unless-stopped
    dns:
      - 223.5.5.5
    environment:
      - TZ=Asia/Shanghai
      - AB_METHOD=Advance
      - PGID=1000 #需要自行修改填入
      - PUID=1000 #需要自行修改填入
      - UMASK=022